name: Reliable Voice CRM Chat APK Build (Gradle 8.4, AndroidX Enabled)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # 1️⃣  Checkout code
      # ---------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------
      # 2️⃣  Unzip project archive
      # ---------------------------
      - name: Unzip project if zipped
        run: |
          if [ -f voice_crm_chat_project_v3.zip ]; then
            unzip -o voice_crm_chat_project_v3.zip -d voice_crm_chat_project_v3
          fi

      # ---------------------------
      # 3️⃣  Set up JDK 17
      # ---------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ---------------------------
      # 4️⃣  Install Gradle 8.4 locally (no sudo, no drift)
      # ---------------------------
      - name: Download and Extract Gradle 8.4
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip
          mkdir -p $HOME/gradle
          unzip -q gradle-8.4-bin.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.4/bin" >> $GITHUB_PATH
          gradle -v

      # ---------------------------
      # 5️⃣  Enable AndroidX + Jetifier permanently
      # ---------------------------
      - name: Enable AndroidX
        run: |
          echo "android.useAndroidX=true" >> voice_crm_chat_project_v3/gradle.properties
          echo "android.enableJetifier=true" >> voice_crm_chat_project_v3/gradle.properties

      # ---------------------------
      # 6️⃣  Add missing resources & icons
      # ---------------------------
      - name: Add placeholder app icons and resources
        run: |
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-anydpi-v26
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-hdpi
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-mdpi
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-xhdpi
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-xxhdpi
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-xxxhdpi
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/values

          # Accent color & app name
          echo '<resources>
              <color name="accent">#00B3B3</color>
              <string name="app_name">Voice CRM Chat</string>
          </resources>' > voice_crm_chat_project_v3/app/src/main/res/values/auto_values.xml

          # Adaptive icon XML
          echo '<?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@color/accent"/>
              <foreground android:drawable="@drawable/ic_mic"/>
          </adaptive-icon>' > voice_crm_chat_project_v3/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

      # ---------------------------
      # 7️⃣  Generate 1×1 px placeholder PNG icons
      # ---------------------------
      - name: Install ImageMagick and generate icons
        run: |
          sudo apt-get update -y
          sudo apt-get install -y imagemagick
          for dir in hdpi mdpi xhdpi xxhdpi xxxhdpi; do
            convert -size 1x1 xc:"#00B3B3" voice_crm_chat_project_v3/app/src/main/res/mipmap-$dir/ic_launcher.png
          done

      # ---------------------------
      # 8️⃣  Build APK
      # ---------------------------
      - name: Build APK
        run: |
          cd voice_crm_chat_project_v3/app
          gradle assembleDebug --no-daemon --stacktrace

      # ---------------------------
      # 9️⃣  Upload result
      # ---------------------------
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCRMChat-debug
          path: voice_crm_chat_project_v3/app/build/outputs/apk/debug/app-debug.apk
