name: Voice CRM Chat – Final Stable Build (No Duplicate Colors)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Unzip project archive if zipped
      - name: Unzip project archive
        run: |
          if [ -f voice_crm_chat_project_v3.zip ]; then
            unzip -o voice_crm_chat_project_v3.zip -d voice_crm_chat_project_v3
          fi

      # 3️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4️⃣ Install Gradle 8.4
      - name: Install Gradle 8.4
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip
          mkdir -p $HOME/gradle
          unzip -q gradle-8.4-bin.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.4/bin" >> $GITHUB_PATH
          gradle -v

      # 5️⃣ Enable AndroidX + Jetifier
      - name: Enable AndroidX and Jetifier
        run: |
          echo "android.useAndroidX=true" >> voice_crm_chat_project_v3/gradle.properties
          echo "android.enableJetifier=true" >> voice_crm_chat_project_v3/gradle.properties

      # 6️⃣ Add missing colors only if not present
      - name: Add required color values (skip if colors.xml exists)
        run: |
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/values
          if [ ! -f voice_crm_chat_project_v3/app/src/main/res/values/colors.xml ]; then
            echo '<resources>
                <color name="teal_200">#03DAC5</color>
                <color name="nav_item_color">#00B3B3</color>
                <color name="white">#FFFFFF</color>
                <color name="black">#000000</color>
            </resources>' > voice_crm_chat_project_v3/app/src/main/res/values/colors.xml
          fi

      # 7️⃣ Install ImageMagick
      - name: Install ImageMagick
        run: sudo apt-get update -y && sudo apt-get install -y imagemagick

      # 8️⃣ Create adaptive launcher icon
      - name: Create adaptive launcher icon
        run: |
          mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-anydpi-v26
          echo '<?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@color/teal_200"/>
              <foreground android:drawable="@drawable/ic_mic"/>
          </adaptive-icon>' > voice_crm_chat_project_v3/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

      # 9️⃣ Generate placeholder icons (unique names)
      - name: Generate placeholder PNG icons
        run: |
          for dir in hdpi mdpi xhdpi xxhdpi xxxhdpi; do
            mkdir -p voice_crm_chat_project_v3/app/src/main/res/mipmap-$dir
            convert -size 1x1 xc:"#00B3B3" voice_crm_chat_project_v3/app/src/main/res/mipmap-$dir/ic_placeholder.png
          done

      # 🔟 Build APK
      - name: Build APK
        run: |
          cd voice_crm_chat_project_v3/app
          gradle assembleDebug --no-daemon --stacktrace --warning-mode=all

      # 1️⃣1️⃣ Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCRMChat-debug
          path: voice_crm_chat_project_v3/app/build/outputs/apk/debug/app-debug.apk
