name: Voice CRM Chat – FINAL VERIFIED BUILD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Detect project folder (handle nested or unzipped)
      - name: Detect project directory
        id: detect
        run: |
          if [ -d "voice_crm_chat_project_v3" ]; then
            echo "dir=voice_crm_chat_project_v3" >> $GITHUB_ENV
          elif [ -f "voice_crm_chat_project_v3.zip" ]; then
            unzip -o voice_crm_chat_project_v3.zip -d voice_crm_chat_project_v3
            echo "dir=voice_crm_chat_project_v3" >> $GITHUB_ENV
          else
            echo "dir=." >> $GITHUB_ENV
          fi

      # 3️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4️⃣ Install Gradle 8.4
      - name: Install Gradle 8.4
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip
          mkdir -p $HOME/gradle
          unzip -q gradle-8.4-bin.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.4/bin" >> $GITHUB_PATH
          gradle -v

      # 5️⃣ AndroidX flags
      - name: Enable AndroidX and Jetifier
        run: |
          echo "android.useAndroidX=true" >> ${{ env.dir }}/gradle.properties
          echo "android.enableJetifier=true" >> ${{ env.dir }}/gradle.properties

      # 6️⃣ Ensure colors.xml exists (absolute verified path)
      - name: Verify or create colors.xml
        run: |
          mkdir -p ${{ env.dir }}/app/src/main/res/values
          cat > ${{ env.dir }}/app/src/main/res/values/colors.xml <<'EOF'
          <resources>
              <color name="teal_200">#03DAC5</color>
              <color name="nav_item_color">#00B3B3</color>
              <color name="accent">#00B3B3</color>
              <color name="white">#FFFFFF</color>
              <color name="black">#000000</color>
          </resources>
          EOF
          echo "✅ colors.xml ensured at ${{ env.dir }}/app/src/main/res/values/colors.xml"

      # 7️⃣ Adaptive launcher icon
      - name: Create adaptive launcher icon
        run: |
          mkdir -p ${{ env.dir }}/app/src/main/res/mipmap-anydpi-v26
          cat > ${{ env.dir }}/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@color/teal_200"/>
              <foreground android:drawable="@drawable/ic_mic"/>
          </adaptive-icon>
          EOF

      # 8️⃣ Build APK
      - name: Build APK
        run: |
          cd ${{ env.dir }}/app
          gradle assembleDebug --no-daemon --stacktrace --warning-mode=all

      # 9️⃣ Upload artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCRMChat-debug
          path: ${{ env.dir }}/app/build/outputs/apk/debug/app-debug.apk
